### ISSUE TITLE
Not handling onFocusGained properly

### ISSUE THREAD

**Issue by zupat** [EdsonBueno/focus_detector#2]
This package treats visibility and focus as synonymous but they are not. 

On android, for example...you'd have to use [onWindowFocusChanged ](https://developer.android.com/reference/android/app/Activity#onWindowFocusChanged(boolean))to detect whether the app has regained focus after switching back to it. 

The clipboard, for example, cannot be accessed until the app is in focus and accessing the clipboard on "onFocusGained" from this package returns null because there is a brief delay between onResume and when the app actually gains focus. The code below can be used to detect focus on android:

```
public void onWindowFocusChanged(boolean hasFocus) {         
     super.onWindowFocusChanged(hasFocus);
     if(hasFocus) 
         Toast.makeText(context, text, duration).show();
 }
```

**Comment by EdsonBueno** [comment]
I agree with you that focus is not a good word.
In the package's context, the word **visibility** is used for when your app is in the foreground but your widget appears/disappears, likely because another screen was pushed on top or the widget was scrolled off the screen.
We use **foreground** to tell you when your widget remains visible within your app but your app is no longer being used by the user.
Lastly, I needed a word to convey a combination of when any of these two events above happened, and by seeing the word **focus** being used [here](https://developer.android.com/guide/components/activities/activity-lifecycle#onresume), I decided to go with it.
I regret that for some reasons, the main one is that people associate the word **focus** with camera or input focus (as in `FocusNode`). But once a package is published, there's no way back. So I guess I'll have to just carry that burden.
I'm sorry for the confusion! There's nothing I can do to help you besides explaining the reasoning behind it, so I'll close the issue. Thank you so much for the comprehension!
